#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commitCount=`git rev-list --all --count`

echo "VITE_COMMIT_COUNT=$commitCount" > .env
echo "VITE_COMMIT_COUNT=$commitCount" > apps/life-logger/.env

git add .env apps/life-logger/.env

exit 0
